spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project?SSL=true
    username:
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lori.pojo

server:
  port: 9000